### ISSUE TITLE
to-do

### ISSUE THREAD

**Issue by ViniciusdSC** [ViniciusdSC/garcom-digital-funcionario#1]
### Páginas
- [ ] Ler Qr Code
- [ ] Liberar conta
- [ ] Login
- [ ] Register
- [ ] Alterar Estabelecimento
- [ ] Configurações da conta

### Ações
- [ ] Login
- [ ] Register
- [ ] Liberar conta
- [ ] Verificar validade do qr code
- [ ] Crud dos dados pessoais
